services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    environment:
      - VITE_API_URL=http://server:3000
    depends_on:
      - server
    command: npm run start

  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run start
